import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { AuthProvider } from "@/lib/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <nav className="border-b border-gray-200 bg-white px-6 py-4">
            <div className="flex gap-6">
              <Link href="/" className="text-gray-900 hover:text-gray-600">
                Home
              </Link>
              <Link href="/user" className="text-gray-900 hover:text-gray-600">
                User
              </Link>
              <Link href="/affiliate" className="text-gray-900 hover:text-gray-600">
                Affiliate
              </Link>
              <Link href="/seller" className="text-gray-900 hover:text-gray-600">
                Seller
              </Link>
              <Link href="/admin" className="text-gray-900 hover:text-gray-600">
                Admin
              </Link>
            </div>
          </nav>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
